name: Canton CI

on: [push, pull_request]

jobs:
  canton-open-source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 11 (Temurin 11)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y unzip curl

      - name: Download Canton Open Source
        run: |
          curl -L https://github.com/digital-asset/daml/releases/download/v2.10.2/canton-open-source-2.10.2.tar.gz -o canton-open-source.tar.gz
          tar -xzf canton-open-source.tar.gz

      - name: Make Canton executable
        run: chmod +x canton-open-source-2.10.2/bin/canton

      - name: Start Canton sandbox with JSON Ledger API
        shell: bash
        run: ./canton-open-source-2.10.2/bin/canton sandbox --json-api-port 7575 &

      - name: Wait for JSON Ledger API to be live
        shell: bash
        run: |
          set -euo pipefail
          for i in {1..60}; do
            if curl -sf http://localhost:7575/livez >/dev/null; then
              echo "JSON Ledger API livez is OK";
              break;
            fi;
            echo "Waiting for JSON Ledger API (attempt $i) ...";
            sleep 2;
          done
          curl -sS http://localhost:7575/livez | sed -e 's/.*/livez: &/'

      - name: Show OpenAPI and ledger end
        shell: bash
        run: |
          set -euo pipefail
          echo "OpenAPI (first 20 lines):"
          curl -sS http://localhost:7575/docs/openapi | head -n 20 || true
          echo
          echo "Ledger end:"
          curl -sS -H "Content-Type: application/json" http://localhost:7575/v2/state/ledger-end || true

      - name: Cleanup
        run: kill $(jobs -p) || true
